### ISSUE TITLE
Invisible terrain by coast on Thenyaw

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#471] opened 2018-12-06 17:14 UTC
## Expected Behavior

There should not be any invisible terrain on Thenyaw.

## Current Behavior

There's a huge section of invisible terrain on Thenyaw by the coast.

![image](https://user-images.githubusercontent.com/30550499/49599706-902c9500-f979-11e8-8d57-b852cd52529b.png)

![image](https://user-images.githubusercontent.com/30550499/49599869-df72c580-f979-11e8-867e-1dcf396cef6f.png)

![image](https://user-images.githubusercontent.com/30550499/49600019-34164080-f97a-11e8-803a-7bad993289e9.png)

## Steps to reproduce

1. Spawn in on Thenyaw.
2. Navigate to the coast.
3. Use scent to bring up compass and head south until you reach invisible terrain.

## Build Information

> **Game Version:** 0.1.51.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment] 2019-01-24 14:26
There was a giant hidden rock in this area that was the cause of this, fixed in version 0.1.52.1.

**Closed by dinosauriac** 2019-01-24 14:26 UTC
Labels: Thenyaw, client
