### ISSUE TITLE
Pressing enter while in the skin customization menu will spawn another dinosaur in the preview area.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#525] opened 2019-01-22 15:44 UTC
## Expected Behavior

Pressing enter without having pressed any of the buttons first should not do anything while in the customization menu.

## Current Behavior

Pressing enter in the customization menu without having clicked on any of the other buttons after pressing confirm in the dinosaur selection menu will spawn another dinosaur in the customization area. You can do this indefinitely and get a bunch of them overlapping eachother. Pressing confirm will spawn you in... but you will have the skin customization menu still open. Pressing confirm again will make your current player dinosaur disappear and despawn you, while also despawning one "clone". Pressing confirm till each of the "clones" have disappeared will get rid of the menu, but you'll be an unmovable camera that serves no purpose at all. The only way to play normally again is to rejoin the server, the respawn button does not help in sandbox. You will log in as the dinosaur you had chosen, though.

Screenshot and original report by MizuSky#3061: https://cdn.discordapp.com/attachments/401465476661641217/537293560425218058/AFCA949C7A4AF95ABF1A53168388C4797409D0D6.png
## Steps to reproduce

Join any server and select a dinosaur that can customize its skin.
Press enter after opening the customization menu (Without pressing any other button in the customization menu)

See how new dinosaurs are spawning in the preview area on top of the original one.

Press confirm. You will "spawn in", but the customization menu will still be open. The original dinosaur will have disappeared, and the clone(s) will be there. 

Pressing confirm again will get rid of a clone. Doing so until all clones have disappeared will get rid of the skin customization menu.

You'll be a camera on the ground with no ability to do anything at all. The only thing you can do is log out or respawn.

Relogging will make you spawn in as the dinosaur you had originally chosen.

## Build Information
> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client,

**Comment by dinosauriac** [comment] 2019-01-25 13:14
It seems like this was caused by the character select menu still receiving input when the customizer was shown. This should be fixed as of revision 3055.

**Closed by dinosauriac** 2019-01-25 13:14 UTC
