### ISSUE TITLE
Extreme Sudden Ambience Transition

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#393] opened 2018-08-12 07:12 UTC
## Expected Behavior

A smooth transition of audio between biomes.

## Current Behavior

A small section of the V3 map currently lacks a smooth gradient ambience while transitioning through the area. This area includes a small pocket in the Southwest directly North of the newest redwood biome region. Coordinates provided in videos.

## Steps to reproduce

Venture to the stretch of hills directly between large swamp and small swamp while sticking close to the mountainside bordering the Northern region of the new redwood biome. Flicking the camera in a 360 degrees will warrant a sudden audio switch between areas.
Ambience Switch Part 1: https://streamable.com/4nemm
Ambience Switch Part 2: https://streamable.com/ewi8w
Ambience Switch Part 3: https://streamable.com/0pkns

**General Area Coordinates A:**
Latitude 291, 327, 688
Longitude 101, 036, 859
Altitude -37, 807, 625

**General Area Coordinates B:**
Latitude 307, 360, 625
Longitude 90, 247, 641
Altitude -34, 560, 672

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment] 2018-08-15 15:35
This is essentially a duplicate of issue #384

**Closed by dinosauriac** 2018-08-15 15:35 UTC
Labels: V3, client
