### ISSUE TITLE
Adult Gallimimus scent animation does not play

### ISSUE THREAD

**Issue by TI-ghostway** [TheIsleGame/bugs#239] opened 2018-06-03 10:39 UTC
## Expected Behavior

When holding Q, Gallilimus should have a scent animation play.

## Current Behavior

Currently, Gallimimus stands still and plays no animation when Q is held.

## Steps to reproduce

1 - Be an adult Gallimimus.
2 - Hold the Q button to activate scent.
3 - Notice that no scent animation plays.

## Build Information

> **Game Version:** 0.1.38.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment] 2018-06-03 18:35
Duplicate of issue #221

**Closed by dinosauriac** 2018-06-03 18:35 UTC
