### ISSUE TITLE
Inter-species chatting

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#44] opened 2018-03-25 17:42 UTC
## Expected Behavior

Players should not be able to talk to those that are different species.

## Current Behavior

Gigas can currently talk to rexes via local chat. (There may be more species - will update this if that's the case.)

## Steps to reproduce

1. Spawn as Giga.
2. Have another player spawn as Rex.
3. Talk to them in local chat.

## Build Information

> **Game Version:** 0.1.35.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment] 2018-03-26 09:00
Fixed in 0.1.35.3

**Closed by looterz** 2018-03-26 09:00 UTC
Labels: client

**Comment by Emanthealmighty** [comment] 2019-04-21 22:41
Retested on 22 April 2019
Gigas and Rexes cannot talk with eachother as intended.
