### ISSUE TITLE
Edible Bushes doesn't switch to empty model after eating it.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#348] opened 2018-07-11 22:06 UTC
## Expected Behavior

Edible bushes to switch to empty model once consumed.

## Current Behavior

Edible Bushes doesn't switch to empty model once consumed.
If you eat a bush while scent is active,scent effect will remain even after scent is no longer active.
 
Video Evidence: https://youtu.be/gG12xD_eItg

## Steps to reproduce

1. Be a herbivore and eat any bush.
2. Notice that once you eat the bush,it won't switch to consumed/empty model.

3. Additionally,you can do step 1 while using scent and you should notice that if you eat the bush while scent is active, scent highlight effect will remain even after scent is no longer active.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2186389/TheIsle.log)

> **Game Version:** 0.1.40.3 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by ExtraHu3** [comment] 2018-07-11 22:30
Originally Reported by: Aeon#1445

**Comment by looterz** [comment] 2018-07-14 22:00
Does this happen for you all the time, or is it a rare issue?

**Comment by ExtraHu3** [comment] 2018-07-14 23:11
It will always happen if you use Scent near the plant you're about to eat.
It will never happen if you don't use Scent near the plant you're about to eat.
My bad for not realizing this and including it in the issue before.
Video Evidence: https://youtu.be/GXD9UIDMEX0

Steps to Reproduce should look like this: 

1.Spawn as a herbivore and find an edible bush.

2.Use scent near the bush and eat it.

3.Notice that once you eat the bush,it won't switch to consumed/empty model.


Note: If you eat the bush while scent is still active,scent highlight effect will remain even after scent is no longer active.

**Comment by looterz** [comment] 2018-07-14 23:55
I can't reproduce this in 0.1.40.4, so it may have been fixed by some other changes made to scent.

**Closed by looterz** 2018-07-14 23:55 UTC
Labels: client, dedicated server

**Comment by Hypno123** [comment] 2018-07-16 18:41
To clarify, it was fixed in 0.1.40.4.
