### ISSUE TITLE
V3: Footprints appear on ocean water's surface

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#197] opened 2018-05-12 19:55 UTC
## Expected Behavior

Footprints do not show up on the water's surface of the ocean

## Current Behavior

When you walk into the ocean water, footprints show up on the surface
![image](https://user-images.githubusercontent.com/32625368/39961087-75636a74-55f4-11e8-90fc-63fa2cf6606d.png)

## Steps to reproduce

Go to V3, walk around in ocean shallows, observe footprints on water's surface

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment] 2018-05-12 20:00
Duplicate of: https://github.com/TheIsleGame/bugs/issues/161

**Closed by dinosauriac** 2018-05-12 20:00 UTC
