### ISSUE TITLE
AI Spawning Issues

### ISSUE THREAD

**Issue by Rapod123** [TheIsleGame/bugs#562] opened 2019-02-15 12:29 UTC
## Expected Behavior

AI to be spawning in accessible places.

## Current Behavior

AI Spawning in inaccessible places. (Inside a rock)

The Rock the AI spawned in is marked on the map with my name (Rapod/Alex) near the canyon.

![ai spawning](https://user-images.githubusercontent.com/39027810/52855881-a34aa680-311a-11e9-9a6c-2c231f33c91d.jpg)

## Steps to reproduce

1. Spawn in. 
2. Casually play the game. 
3. Wait until you find AI that has spawned inside a rock. 

This one is very tricky to reproduce but this isn't the first time I have experienced it. 

## Build Information

(https://github.com/TheIsleGame/bugs/files/2869160/TheIsle.log)

> **Game Version:** 0.1.52.6

> **Operating System:** Windows

> **Network Role:** Client

**Comment by Hypno123** [comment] 2019-02-15 15:53
This is a duplicate of #331

**Closed by Hypno123** 2019-02-15 15:53 UTC
Labels: client
