### ISSUE TITLE
Thenyaw Threshold/border near Ocean makes trees disappear

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#368] opened 2018-07-22 04:47 UTC
## Expected Behavior

No matter where you are on the map, Trees (especially in your vicinity) should not disappear.

## Current Behavior

There seems to be an invisible border/threshold that when you cross it, the trees in all of Thenyaw disappear, and when you cross back over it, they will reappear.

https://clips.twitch.tv/LitigiousPuzzledSalamanderDatSheffy

## Steps to reproduce

Be any dinosaur. Run from swamp towards the ocean. You will notice on your way towards the ocean, you will hit a border which will make the trees disappear, and if you turn around and cross it heading back towards the swamp, the trees with reappear.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.6 (dev 3)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment] 2018-07-22 16:40
This was most likely caused by the same issue as this #365

**Comment by dinosauriac** [comment] 2018-07-23 21:48
Should be fixed with the most recent build.

**Comment by Hypno123** [comment] 2018-10-27 00:37
Fixed.

**Closed by Hypno123** 2018-10-27 00:37 UTC
Labels: Thenyaw, client
