### ISSUE TITLE
Adult Galli IK Legs- Bow-legged up and down hills

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#536] opened 2019-01-27 20:34 UTC
## Expected Behavior

Adult Gallimimus has natural looking leg movements whether going up or down hills, or on a straight surface.

## Current Behavior

The Adult Galli will have a bow-legged appearance when going up or down any sort of terrain, even if the incline is very mild. This is especially noticable when viewing the galli directly from the rear (Tail to camera)

## Steps to reproduce

Be an adult gallimimus and pay attention to the angle of the legs/ankles when going up/down/level on terrain, and notice the difference.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Emanthealmighty** [comment] 2019-01-30 18:30
I recently tested the galli and gone up and down every hill I could find, but it didn't seem to do any weird thing with its legs. I think it's safe to say that the problem is fixed

**Comment by Hypno123** [comment] 2019-01-30 18:35
Fixed in 0.1.52.3

**Closed by Hypno123** 2019-01-30 18:35 UTC
Labels: art, client
