### ISSUE TITLE
You can Jump When Making a Nest (found by Death)

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#517] opened 2019-01-18 06:25 UTC
## Expected Behavior

A nesting animation shouldn't continue uninterrupted if you jump in the middle of it

## Current Behavior

you can spam jump and your dino will hop into the air, still playing the nest-building animation

## Steps to reproduce

Be a dryo, gali, or utah and then place a nest. Press spacebar while making it.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.51.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment] 2019-01-18 08:03
Duplicate of #505 which has been fixed for next patch.

**Closed by Hypno123** 2019-01-18 08:03 UTC
Labels: duplicate
